name: 更新 Clash/CloudflareCIDR.list

on:
  schedule:
    - cron: '5 * */5 * *'
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download and validate CIDRs
        run: python CloudflareCIDR-main.py

      - name: Check for changes and commit
        run: bash scripts/commit-list-updates.sh "Downloaded file on $(date '+%Y/%m/%d %H:%M:%S')" Clash/CloudflareCIDR.list CloudflareCIDR.txt
